#include <furi.h>
#include <furi_hal_resources.h>
#include <furi_hal_interrupt.h>
/* generated by fbt from .png files in images folder */
#include <isr_test_icons.h>

const GpioPin test_gpio = {.port = GPIOA, .pin = LL_GPIO_PIN_7};

volatile uint32_t start = 0;
volatile uint32_t delta = 0;

void tim_init(void) {
    // Timer: base
    LL_TIM_InitTypeDef TIM_InitStruct = {0};
    TIM_InitStruct.Prescaler = 64 - 1;
    TIM_InitStruct.CounterMode = LL_TIM_COUNTERMODE_UP;
    TIM_InitStruct.Autoreload = 0x7FFFFFFE;
    TIM_InitStruct.ClockDivision = LL_TIM_CLOCKDIVISION_DIV4;
    LL_TIM_Init(TIM2, &TIM_InitStruct);

    // Timer: advanced
    LL_TIM_SetClockSource(TIM2, LL_TIM_CLOCKSOURCE_INTERNAL);
    LL_TIM_DisableARRPreload(TIM2);
    LL_TIM_SetTriggerInput(TIM2, LL_TIM_TS_TI1FP1);
    LL_TIM_SetSlaveMode(TIM2, LL_TIM_SLAVEMODE_DISABLED);
    LL_TIM_SetTriggerOutput(TIM2, LL_TIM_TRGO_RESET);
    LL_TIM_DisableDMAReq_TRIG(TIM2);
    LL_TIM_DisableIT_TRIG(TIM2);
    LL_TIM_EnableMasterSlaveMode(TIM2);

    // Start timer
    LL_TIM_SetCounter(TIM2, 0);
    LL_TIM_EnableCounter(TIM2);
}

void test_callback(void* ctx) {
    UNUSED(ctx);
    if(furi_hal_gpio_read(&test_gpio)) {
        start = TIM2->CNT;
    } else {
        delta = TIM2->CNT - start;
        //TIM2->CNT = 0;
    }
}

int32_t isr_test_app(void* p) {
    tim_init();
    UNUSED(p);

    FURI_LOG_I("TEST", "Hello world");

    furi_hal_gpio_init(&test_gpio, GpioModeInterruptRiseFall, GpioPullUp, GpioSpeedLow);

    furi_hal_gpio_add_int_callback(&test_gpio, test_callback, NULL);
    furi_hal_gpio_enable_int_callback(&test_gpio);

    uint32_t i = furi_get_tick();
    while(furi_get_tick() - i < 10000) {
        FURI_LOG_I("TEST", "Delta: %ld", delta);
        furi_delay_ms(10);
    }

    furi_hal_gpio_disable_int_callback(&test_gpio);
    furi_hal_gpio_init(&test_gpio, GpioModeAnalog, GpioPullNo, GpioSpeedLow);

    return 0;
}
